### ISSUE TITLE
how to dynamic create/delete or hide/show composable component in Jetpack Compose

### ISSUE THREAD

**Issue by chengstone** [nikit19/AnimationsJepackCompose#1]
hi, Nikit

I saw your great demo and the blog, I've learned a lot.
Something I'd like to ask you a question, just like title : 
how to dynamic open/close a list(some component create/delete or hide/show in the list item) in Jetpack Compose?

I think this is a challenge using the Jetpack Compose, it feels like:
<img width="294" alt="sample" src="https://user-images.githubusercontent.com/6791799/79738871-54a92580-8338-11ea-826f-b5cae833593e.png">

excuse me for bothering you,
I appreciate your response

Thank you

**Comment by nikit19** [comment]
Hey thanks for the kind words. 
I guess you can make the above UI by maintaining the state of the toggle button and then manipulate your UI based on the state of your button.

Something similar has been done in this repo https://github.com/android/compose-samples
where they see if the button is selected or not.

**Comment by chengstone** [comment]
yes, you are right, I solved using Toggleable, thank you very much
